# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -X ultravioletcmd.version={{.Version}}
release:
  draft: true
  name_template: '{{.Version}}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Tag }}-next'
archives:
  - name_template: 'ultraviolet-{{.Os}}-{{.Arch}}-{{.Version}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ignore:'
dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
    - "realdragonium/ultraviolet:latest"
    - "realdragonium/ultraviolet:{{ .Tag }}"
    - "ghcr.io/realdragonium/ultraviolet:{{ .Tag }}"
