# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -X ultravioletcmd.version={{.Version}}
release:
  draft: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
archives:
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
